repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-added-large-files
-   repo: local
    hooks:
    -   id: black
        name: Format code
        entry: poetry run black
        language: system
        types: [python]
    -   id: isort
        name: Sort imports
        entry: poetry run isort
        language: system
        types: [python]
    -   id: lint
        name: Lint code
        entry: poetry run pylint
        language: system
        types: [python]
